"""Add options column to questions

Revision ID: 4e62ceb8be41
Revises: 
Create Date: 2023-11-28 14:38:26.659220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e62ceb8be41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('quizes')
    op.drop_table('gamesessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamesessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userscore', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizes.id'], name='fk_gamesessions_quiz_id_quizes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_gamesessions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quizcategory', sa.VARCHAR(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_quizes_question_id_questions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(), nullable=True),
    sa.Column('answer', sa.VARCHAR(), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizes.id'], name='fk_questions_quiz_id_quizes'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
